add blocks personal information, languages, skills, certifications
alexMbicycle/cv-gen-react pull request #10
Opened 2022-07-27 11:57 UTC by Bakunova-Olya

2022-07-27 15:21 UTC, alexMbicycle requested changes
Remove all sx to styled just if is in the sx a single parameter you can leave it.

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/projects/components/SkillsToolsDialog.tsx
>  } from 'react';
to single line please

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +  return (
Ask @varaMbicycle hoe to divide logically blocks of code. Spacing reqired.

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +        margin: '1.8rem 2.4rem 0',
theme.spacing(...)

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +        borderRadius: '0.2rem',
theme.shape.borderRadius

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +
no empty lines

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +            borderRadius: '50%',
replace to styled and set width and height in px

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +              marginLeft: '0.8rem',
call function inside and set theme.spacing or better replace to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +            CERTIFICATIONS
All literals store in constants.ts

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +            Date
as previous

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +                    marginRight: '0.6rem',
repalce to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +            <Grid item xs={4} sx={{ textAlign: 'center' }}><Typography>{certificate.id}</Typography></Grid>
Look how plased Typography component, Failing code readability

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +  return (
Spaces

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +        borderRadius: '0.2rem',
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +        spacing={1}
if there are two props please place them in one line
`<Grid container spacing={1} />`

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +            borderRadius: '50%',
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +
no empty line

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +            }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +            LANGUAGES
to constants

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +            Level
to constants

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +                  }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Languages.tsx
> +            <Grid item xs={4} sx={{ textAlign: 'center' }}><Typography>{language.level}</Typography></Grid>
Incorrect elements position

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalDetails.tsx
> +    >
You can use 
`<Container maxWidth="lg" /> `
this Grid instead
Also as I remenber you can add `component={Grid}` prop

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalInformation.tsx
> +    <Paper
Spacings

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalInformation.tsx
> +        borderRadius: '0.2rem',
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalInformation.tsx
> +      >
single line

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalInformation.tsx
> +            }}
styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/PersonalInformation.tsx
> +            SUMMARY OF QUALIFICATION
to constants

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +  return (
spacing required

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +
no empty line

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +        alignItems: 'center',
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +            }}
To styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +            }}
same as previous

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +export default RatingLanguage;
You are using props, memoizing required.

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +      }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +      >
Single line

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +          }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +          <SchoolIcon color="primary" sx={{ margin: '0.7rem' }} />
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +            }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +            SKILLS
to constants

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +                          }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/TopBox.tsx
> +
no empty row

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/TopBox.tsx
> +      }}
to styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/TopBox.tsx
> +      spacing={0}
remove. Zero by default

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/TopBox.tsx
> +
no empty row and replace to styled.ts

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/TopBox.tsx
> +        />
Styled

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/index.tsx
> +  useEffect(() => {
Spacings

2022-07-27 15:21 UTC, alexMbicycle commented on src/containers/main-page/preview/index.tsx
> +
no empty line

2022-08-02 18:59 UTC, Bakunova-Olya commented
All bug fixed

2022-08-03 12:54 UTC, alexMbicycle requested changes

2022-08-03 12:54 UTC, alexMbicycle commented on src/containers/main-page/preview/Certifications.tsx
> +          <ArticleIcon color="primary" sx={{ margin: theme.spacing(1.75) }} />
![image](https://user-images.githubusercontent.com/63092716/182612130-3ee49613-e90c-44d6-ba1f-bb9efde967fa.png)

Please change everywhere. Using extra dependencies is not good approach

2022-08-03 12:54 UTC, alexMbicycle commented on src/containers/main-page/preview/RatingLanguage.tsx
> +import { BoxRatingStyled, RectangleBlueIconStyled, RectangleIconStyled } from '../styled';
```
import React from 'react';
import { Rating } from '@mui/material';

import { Labels } from '../cv-form/components/fields/languages/components/utils/level.enum';

import { BoxRatingStyled, RectangleBlueIconStyled, RectangleIconStyled } from '../styled';
```

2022-08-03 12:54 UTC, alexMbicycle commented on src/containers/main-page/preview/Skills.tsx
> +import {
```
import { useEffect } from 'react';
import { useIsFetching } from 'react-query';

import { Grid, Typography } from '@mui/material';

import theme from '../../../common/theme';
import { useUserFromDb } from '../cv-form/components/fields/personal-information/lib/query-hooks';
import { CV_FORM_STEPS } from '../cv-form/utils/constants';
import {
  PaperWrapperStyled, BoxWrapperStyled, CircleIconStyled,
   SectionTitle, SkillsGrid, SchoolIconStyled,
} from '../styled';

```

2022-08-04 10:02 UTC, Bakunova-Olya commented
All bug fixed

2022-08-05 06:33 UTC, alexMbicycle approved these changes

2022-08-05 06:36 UTC, merged