Feature/skills
alexMbicycle/cv-gen-react pull request #11
Opened 2022-07-28 11:31 UTC by varaMbicycle

- resolved issue to edit name skill
- changed addTool button position
- added scroll func to tool list

2022-07-29 10:06 UTC, alexMbicycle requested changes

2022-07-29 10:06 UTC, alexMbicycle commented on src/common/providers/AppProvider.tsx
> +      {/* <React.StrictMode> */}
Please delete from the code

2022-07-29 10:06 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/components/tool/Skill.tsx
> +        {/* </Grid> */}
Do not use commented code in the code.

2022-07-29 10:06 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/components/tool/index.tsx
> +  const listRef = useRef<HTMLDivElement>(null);
Should be placed before functions with space

2022-08-03 12:46 UTC, alexMbicycle requested changes

2022-08-03 12:46 UTC, alexMbicycle commented on src/common/components/text-field-outlined/index.tsx
>  import { TextFieldStyled } from './styled';
Should look like this

```
import React, { memo } from 'react';
import { OutlinedTextFieldProps } from '@mui/material';

import { TextFieldStyled } from './styled';
```

2022-08-03 12:46 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/components/tool/index.tsx
> +} from 'react';
```
import React, {
  memo, useCallback, 
  useEffect, useRef, useState,
} from 'react';
```

2022-08-03 12:46 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/components/tool/index.tsx
> +} from '@mui/material';
```
import {
  Grid, Typography, SelectChangeEvent, 
  AccordionSummary, AccordionDetails,
} from '@mui/material';
```

2022-08-03 12:46 UTC, alexMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/utils/styled.ts
> +  Box, Button, Divider, Grid, styled, Typography, Accordion,
please drop by three items

2022-08-03 12:51 UTC, varaMbicycle commented on src/containers/main-page/cv-form/components/fields/skills/utils/styled.ts
> +  Box, Button, Divider, Grid, styled, Typography, Accordion,
I will know for future

2022-08-03 12:55 UTC, alexMbicycle approved these changes

2022-08-03 12:55 UTC, merged